// This file is auto-generated by @hey-api/openapi-ts

export type ActivitiesPublic = {
    data: Array<ActivityPublic>;
    count: number;
};

export type ActivityCreate = {
    title: string;
    exercises?: (Array<(string)> | null);
    user_id: string;
};

export type ActivityPublic = {
    title: string;
    exercises?: (Array<(string)> | null);
    user_id: string;
    id: string;
};

export type ActivityUpdate = {
    title?: (string | null);
    exercises?: (Array<(string)> | null);
    user_id: string;
};

export type AdminUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type Body_login_access_token_api_v1_login_access_token_post = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type Difficulty = 'easy' | 'medium' | 'hard';

export type ExerciseCategory = 'strength' | 'cardio' | 'flexibility' | 'balance' | 'other';

export type ExerciseCreate = {
    title: string;
    description?: (string | null);
    category?: (ExerciseCategory | null);
    muscle_group?: (MuscleGroup | null);
    reps?: (number | null);
    sets?: (number | null);
    duration?: (number | null);
    difficulty?: (Difficulty | null);
    image_url?: (string | null);
    video_url?: (string | null);
    is_active?: boolean;
};

export type ExercisePublic = {
    title: string;
    description?: (string | null);
    category?: (ExerciseCategory | null);
    muscle_group?: (MuscleGroup | null);
    reps?: (number | null);
    sets?: (number | null);
    duration?: (number | null);
    difficulty?: (Difficulty | null);
    image_url?: (string | null);
    video_url?: (string | null);
    is_active?: boolean;
    id: string;
    owner_id: string;
};

export type ExercisesPublic = {
    data: Array<ExercisePublic>;
    count: number;
};

export type ExerciseUpdate = {
    title?: (string | null);
    description?: (string | null);
    category?: (ExerciseCategory | null);
    muscle_group?: (MuscleGroup | null);
    reps?: (number | null);
    sets?: (number | null);
    duration?: (number | null);
    difficulty?: (Difficulty | null);
    image_url?: (string | null);
    video_url?: (string | null);
    is_active?: (boolean | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type Message = {
    message: string;
};

export type MuscleGroup = 'chest' | 'back' | 'legs' | 'arms' | 'shoulders' | 'core' | 'full_body' | 'other';

export type NewPassword = {
    token: string;
    new_password: string;
};

export type Sex = 'male' | 'female' | 'other';

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdateExercisePerformanceRequest = {
    exercise_id: string;
    date: string;
    performance: number;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserActivity = {
    id: string;
    date: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    mobile_number?: (string | null);
    date_of_birth?: (string | null);
    weight?: (number | null);
    height?: (number | null);
    notes?: (string | null);
    sex?: (Sex | null);
    role?: UserRole;
    exercises?: Array<UserExercise>;
    activities?: Array<UserActivity>;
    password: string;
};

export type UserExercise = {
    id: string;
    performance?: {
        [key: string]: (number);
    };
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    mobile_number?: (string | null);
    date_of_birth?: (string | null);
    weight?: (number | null);
    height?: (number | null);
    notes?: (string | null);
    sex?: (Sex | null);
    role?: UserRole;
    exercises?: Array<UserExercise>;
    activities?: Array<UserActivity>;
    id: string;
};

export type UserRole = 'user' | 'admin' | 'trainer';

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: (boolean | null);
    is_superuser?: (boolean | null);
    full_name?: (string | null);
    mobile_number?: (string | null);
    date_of_birth?: (string | null);
    weight?: (number | null);
    height?: (number | null);
    notes?: (string | null);
    sex?: (Sex | null);
    role?: (UserRole | null);
    exercises?: (Array<UserExercise> | null);
    activities?: (Array<UserActivity> | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
    mobile_number?: (string | null);
    date_of_birth?: (string | null);
    weight?: (number | null);
    height?: (number | null);
    notes?: (string | null);
    sex?: (Sex | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type ReadActivitiesApiV1ActivitiesGetData = {
    limit?: number;
    skip?: number;
    userId?: string;
};

export type ReadActivitiesApiV1ActivitiesGetResponse = (ActivitiesPublic);

export type CreateActivityApiV1ActivitiesPostData = {
    requestBody: ActivityCreate;
};

export type CreateActivityApiV1ActivitiesPostResponse = (ActivityPublic);

export type ReadActivityApiV1ActivitiesIdGetData = {
    id: string;
};

export type ReadActivityApiV1ActivitiesIdGetResponse = (ActivityPublic);

export type UpdateActivityApiV1ActivitiesIdPutData = {
    id: string;
    requestBody: ActivityUpdate;
};

export type UpdateActivityApiV1ActivitiesIdPutResponse = (ActivityPublic);

export type DeleteActivityApiV1ActivitiesIdDeleteData = {
    id: string;
};

export type DeleteActivityApiV1ActivitiesIdDeleteResponse = (Message);

export type AddExerciseToActivityApiV1ActivitiesIdExercisesExerciseIdPostData = {
    exerciseId: string;
    id: string;
};

export type AddExerciseToActivityApiV1ActivitiesIdExercisesExerciseIdPostResponse = (ActivityPublic);

export type RemoveExerciseFromActivityApiV1ActivitiesIdExercisesExerciseIdDeleteData = {
    exerciseId: string;
    id: string;
};

export type RemoveExerciseFromActivityApiV1ActivitiesIdExercisesExerciseIdDeleteResponse = (ActivityPublic);

export type AssignActivityToUserApiV1ActivitiesAssignActivityIdPostData = {
    activityId: string;
    date: string;
};

export type AssignActivityToUserApiV1ActivitiesAssignActivityIdPostResponse = (Message);

export type UpdateActivityAssignmentApiV1ActivitiesAssignActivityIdPutData = {
    activityId: string;
    newDate: string;
    oldDate: string;
};

export type UpdateActivityAssignmentApiV1ActivitiesAssignActivityIdPutResponse = (Message);

export type UnassignActivityFromUserApiV1ActivitiesUnassignActivityIdDeleteData = {
    activityId: string;
    date: string;
};

export type UnassignActivityFromUserApiV1ActivitiesUnassignActivityIdDeleteResponse = (Message);

export type GetExercisesForDayApiV1ActivitiesExercisesUserIdDateGetData = {
    date: string;
    userId: string;
};

export type GetExercisesForDayApiV1ActivitiesExercisesUserIdDateGetResponse = (unknown);

export type CreateUserApiV1AdminUsersPostData = {
    requestBody: AdminUserCreate;
};

export type CreateUserApiV1AdminUsersPostResponse = (UserPublic);

export type LoginApiV1GetResponse = (unknown);

export type LoginAccessTokenApiV1LoginAccessTokenPostData = {
    formData: Body_login_access_token_api_v1_login_access_token_post;
};

export type LoginAccessTokenApiV1LoginAccessTokenPostResponse = (Token);

export type TestTokenApiV1LoginTestTokenPostResponse = (UserPublic);

export type RecoverPasswordApiV1PasswordRecoveryEmailPostData = {
    email: string;
};

export type RecoverPasswordApiV1PasswordRecoveryEmailPostResponse = (Message);

export type ResetPasswordApiV1ResetPasswordPostData = {
    requestBody: NewPassword;
};

export type ResetPasswordApiV1ResetPasswordPostResponse = (Message);

export type RecoverPasswordHtmlContentApiV1PasswordRecoveryHtmlContentEmailPostData = {
    email: string;
};

export type RecoverPasswordHtmlContentApiV1PasswordRecoveryHtmlContentEmailPostResponse = (string);

export type ReadExercisesApiV1ExercisesGetData = {
    limit?: number;
    skip?: number;
};

export type ReadExercisesApiV1ExercisesGetResponse = (ExercisesPublic);

export type CreateExerciseApiV1ExercisesPostData = {
    requestBody: ExerciseCreate;
};

export type CreateExerciseApiV1ExercisesPostResponse = (ExercisePublic);

export type ReadExerciseApiV1ExercisesIdGetData = {
    id: string;
};

export type ReadExerciseApiV1ExercisesIdGetResponse = (ExercisePublic);

export type UpdateExerciseApiV1ExercisesIdPutData = {
    id: string;
    requestBody: ExerciseUpdate;
};

export type UpdateExerciseApiV1ExercisesIdPutResponse = (ExercisePublic);

export type DeleteExerciseApiV1ExercisesIdDeleteData = {
    id: string;
};

export type DeleteExerciseApiV1ExercisesIdDeleteResponse = (Message);

export type ReadItemsApiV1ItemsGetData = {
    limit?: number;
    skip?: number;
};

export type ReadItemsApiV1ItemsGetResponse = (ItemsPublic);

export type CreateItemApiV1ItemsPostData = {
    requestBody: ItemCreate;
};

export type CreateItemApiV1ItemsPostResponse = (ItemPublic);

export type ReadItemApiV1ItemsIdGetData = {
    id: string;
};

export type ReadItemApiV1ItemsIdGetResponse = (ItemPublic);

export type UpdateItemApiV1ItemsIdPutData = {
    id: string;
    requestBody: ItemUpdate;
};

export type UpdateItemApiV1ItemsIdPutResponse = (ItemPublic);

export type DeleteItemApiV1ItemsIdDeleteData = {
    id: string;
};

export type DeleteItemApiV1ItemsIdDeleteResponse = (Message);

export type ReadUsersApiV1UsersGetData = {
    limit?: number;
    skip?: number;
};

export type ReadUsersApiV1UsersGetResponse = (UsersPublic);

export type CreateUserApiV1UsersPostData = {
    requestBody: UserCreate;
};

export type CreateUserApiV1UsersPostResponse = (UserPublic);

export type ReadUserMeApiV1UsersMeGetResponse = (UserPublic);

export type DeleteUserMeApiV1UsersMeDeleteResponse = (Message);

export type UpdateUserMeApiV1UsersMePatchData = {
    requestBody: UserUpdateMe;
};

export type UpdateUserMeApiV1UsersMePatchResponse = (UserPublic);

export type UpdatePasswordMeApiV1UsersMePasswordPatchData = {
    requestBody: UpdatePassword;
};

export type UpdatePasswordMeApiV1UsersMePasswordPatchResponse = (Message);

export type ReadUserByIdApiV1UsersUserIdGetData = {
    userId: string;
};

export type ReadUserByIdApiV1UsersUserIdGetResponse = (UserPublic);

export type UpdateUserApiV1UsersUserIdPatchData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UpdateUserApiV1UsersUserIdPatchResponse = (UserPublic);

export type DeleteUserApiV1UsersUserIdDeleteData = {
    userId: string;
};

export type DeleteUserApiV1UsersUserIdDeleteResponse = (Message);

export type UpdateExercisePerformanceApiV1UsersMeExercisePerformancePatchData = {
    requestBody: UpdateExercisePerformanceRequest;
};

export type UpdateExercisePerformanceApiV1UsersMeExercisePerformancePatchResponse = (Message);